# Copyright (c) Stephen Bates, 2022
#
# Update for Linux kernel development. Note we setup the linux kernel
# remotes but do not fetch or clone as this takes a long time. The user
# can do this later

- name: Install kernel build pre-requisites and update if requested
  ansible.builtin.package:
    update_cache: "{{ update_cache }}"
    name:
      - bison
      - flex
      - libelf-dev
      - libssl-dev
  become: yes

- name: Checkout kernel-tools repo
  ansible.builtin.git:
    repo: https://github.com/sbates130272/kernel-tools.git
    dest: ~/kernel
    accept_hostkey: yes
    force: yes

- name: Remove the src folder when forcing
  ansible.builtin.file:
    path: ~/kernel/src
    state: absent
  when: force|bool

- name: Ensure a kernel source exists
  ansible.builtin.file:
    path: ~/kernel/src
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Perform a git init in source folder
  ansible.builtin.shell:
    cmd: git init
    chdir: ~/kernel/src

- name: Ensure remotes are added
  git_config:
    repo: ~/kernel/src/
    scope: 'local'
    name: 'remote.{{ item.name }}.url'
    value: '{{ item.remote }}'
  loop:
    - { name: 'linus', remote: "{{ linus_remote }}" }
    - { name: 'stable', remote: "{{ stable_remote }}" }

- name: Ensure fetching gets all branches
  git_config:
    repo: ~/kernel/src/
    scope: 'local'
    name: 'remote.{{ item }}.fetch'
    value: "+refs/heads/*:refs/remotes/{{ item }}/*"
  loop:
    - linus
    - stable
