# Copyright (c) Stephen Bates, 2022
#
# Clone and update for Linux kernel development. Note we can checkout
# the Linux repo but only if the clone variable is set to true.

- name: Checkout kernel-tools repo
  ansible.builtin.git:
    repo: https://github.com/sbates130272/kernel-tools.git
    dest: ~/kernel
    accept_hostkey: yes
    force: yes

- name: Create a kernel source folder when not cloning
  ansible.builtin.file:
    path: ~/kernel/src
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  when: not clone

- name: Ensure no kernel source folder when cloning
  ansible.builtin.file:
    path: ~/kernel/src
    state: absent
  when: clone

- name: Copy over the Linux kernel git bundle script when cloning
  ansible.builtin.get_url:
    url: '{{ clone_script }}'
    dest: /tmp/linux-bundle-clone
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0775"
  when: clone

- name: Clone the Linux kernel Linus repo (if it has not already been cloned) via git bundle (slow!!)
  ansible.builtin.command:
    chdir: ~/kernel
    cmd: /tmp/linux-bundle-clone '{{ linus_remote }}' src '{{ branch_checkout }}'
    creates: ~/kernel/src/MAINTAINERS
  when: clone

- name: Perform a git init in source folder when not cloning
  ansible.builtin.shell:
    cmd: git init
    chdir: ~/kernel/src
  when: not clone

- name: Ensure linus remote is added when not cloning
  git_config:
        repo: ~/kernel/src/
        scope: 'local'
        name: 'remote.linus.url'
        value: '{{ linus_remote }}'
  when: not clone

- name: Ensure stable remote is added
  git_config:
        repo: ~/kernel/src/
        scope: 'local'
        name: 'remote.stable.url'
        value: '{{ stable_remote }}'
