---
# Copyright (c) Stephen Bates, 2022
#
# Update for Linux kernel development. Note we setup the linux kernel
# remotes but do not fetch or clone as this takes a long time. The user
# can do this later

- name: Install kernel build pre-requisites and update if requested
  ansible.builtin.package:
    update_cache: true
    state: present
    name:
      - bison
      - flex
      - libelf-dev
      - libncurses-dev
      - libssl-dev
  become: true

- name: Ensure Projects folder exists.
  ansible.builtin.file:
    path: ~/Projects
    state: directory
    mode: "0755"

- name: Checkout kernel-tools repo
  ansible.builtin.git:
    repo: "{{ (username == 'batesste') | ternary('git@github.com:sbates130272/kernel-tools.git', 'https://github.com/sbates130272/kernel-tools.git') }}"
    dest: ~/Projects/kernel
    accept_hostkey: true
    force: true
    version: "{{ kernel_setup_tools_sha }}"

- name: Remove the src folder when forcing
  ansible.builtin.file:
    path: ~/Projects/kernel/src
    state: absent
  when: kernel_setup_force|bool

- name: Ensure a kernel source exists
  ansible.builtin.file:
    path: ~/Projects/kernel/src
    state: directory
    mode: "0755"

- name: Perform a git init in source folder
  ansible.builtin.command:
    cmd: git init
    chdir: ~/Projects/kernel/src
    creates: ~/kernel/src/.git

- name: Ensure remotes are added
  community.general.git_config:
    repo: ~/Projects/kernel/src/
    scope: local
    name: remote.{{ item.name }}.url
    value: "{{ item.remote }}"
  loop:
    - { name: linus, remote: "{{ kernel_setup_linus_remote }}" }
    - { name: stable, remote: "{{ kernel_setup_stable_remote }}" }

- name: Ensure fetching gets all branches
  community.general.git_config:
    repo: ~/Projects/kernel/src/
    scope: local
    name: remote.{{ item }}.fetch
    value: +refs/heads/*:refs/remotes/{{ item }}/*
  loop:
    - linus
    - stable
