---
# Copyright (c) Stephen Bates, 2022
#
# Setup the target system(s) for QEMU. Note we do this regardless of
# if KVM (or some other virtualization acceleration is available of
# not). We install most of the QEMU user and system code and also
# install libvirt and virsh. We also checkout the qemu-minimal
# project. Much of this role is based on [1].
#
# [1]: https://www.linuxtechi.com/how-to-install-kvm-on-ubuntu-22-04/

- name: Install packages needed for QEMU and libvirt
  ansible.builtin.package:
    update_cache: true
    state: present
    name:
      - bridge-utils
      - cloud-image-utils
      - cpu-checker
      - guestfs-tools
      - libnss-libvirt
      - libvirt-clients
      - libvirt-daemon-system
      - qemu-kvm
      - virt-manager
      - virtinst
  become: true

- name: Add user to virt groups
  ansible.builtin.user:
    name: "{{ username }}"
    groups: kvm, libvirt
    append: true
  become: true

- name: Enable access to images folder in AppArmour
  ansible.builtin.lineinfile:
    path: /etc/apparmor.d/abstractions/libvirt-qemu
    line: "  /var/lib/libvirt/images/* rwk,"
  become: true

- name: Check for libvirt_guest in nsswitch.conf
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    regex: ^hosts:.*libvirt_guest*
    state: absent
  check_mode: true
  changed_when: false
  register: libvirt_guest
  become: false

- name: Enable libvirt_guest dns via nss
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    regex: ^(hosts:.*)
    line: \1 libvirt_guest
    backrefs: true
  become: true
  when: not libvirt_guest.found

- name: Start relevant systemd services
  ansible.builtin.systemd:
    name: libvirtd
    state: restarted
    daemon_reload: true
    enabled: true
  become: true

- name: Ensure Projects folder exists.
  ansible.builtin.file:
    path: ~/Projects
    state: directory
    mode: "0755"

- name: Clone the qemu-minimal Github repo
  ansible.builtin.git:
    repo: "{{ (username == 'batesste') | ternary('git@github.com:sbates130272/qemu-minimal.git', 'https://github.com/sbates130272/qemu-minimal.git') }}"
    dest: ~/Projects/qemu-minimal
    force: "{{ qemu_setup_force }}"
    version: "{{ qemu_setup_qemu_minimal_sha }}"
