---
galaxy_info:
  author: Stephen Bates
  company: Raithlin Semiconductors
  role_name: kernel_setup
  description: >-
    Install kernel build tools and clone kernel sources
  license: Apache-2.0
  min_ansible_version: "8.2.0"
  platforms:
    - name: Ubuntu
      versions:
        - noble
        - resolute
  galaxy_tags:
    - kernel
    - development
    - linux

dependencies: []
