---
galaxy_info:
  author: Stephen Bates
  company: Raithlin Semiconductors
  role_name: mutt_setup
  description: >-
    Setup mutt email client with OAuth2
  license: Apache-2.0
  min_ansible_version: "8.2.0"
  platforms:
    - name: Ubuntu
      versions:
        - noble
        - resolute
  galaxy_tags:
    - email
    - mutt

dependencies: []
