---
# Copyright (c) Stephen Bates, 2026
#
# SPDX-License-Identifier: Apache-2.0
#

username: batesste
user_setup_motd: true
rdma_setup_install_rdma_exporter: true
rdma_setup_motd: true
nvme_exporter_setup_install: true
