---
collections:
  - name: ansible.posix
    version: 1.6.2
  - name: community.general
    version: 10.0.1
  - name: community.libvirt
    version: 1.3.0

roles:
  - name: geerlingguy.docker
    version: 7.4.1
  - name: mrlesmithjr.netplan
    version: v0.4.2
