# Copyright (c) Stephen Bates, 2022
#
# Set up the command line tool mutt with my sbates@raithlin.com
# email. This enables the receiving and sending of email. Sending is
# especially useful for open-source patches for things like the Linux
# kernel and fio.
#
# Note we assume mutt is already installed.
#
# See this Role's README.md for more information.
#

- name: Create the mutt headers folder for raithlin
  ansible.builtin.file:
    path: ~/.mutt/cache/raithlin/headers
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Create the mutt headers folder for gmail
  ansible.builtin.file:
    path: ~/.mutt/cache/gmail/headers
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Create the mutt bodies folder for raithlin
  ansible.builtin.file:
    path: ~/.mutt/cache/raithlin/bodies
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Create the mutt tmp folder
  ansible.builtin.file:
    path: ~/.mutt/tmp
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Create the mutt language folder
  ansible.builtin.file:
    path: ~/.mutt/lang
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Create the mutt scripts folder
  ansible.builtin.file:
    path: ~/.mutt/scripts
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Create the mutt tokens folder
  ansible.builtin.file:
    path: ~/.mutt/tokens
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Create the mutt bodies folder for gmail
  ansible.builtin.file:
    path: ~/.mutt/cache/gmail/bodies
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Create the mutt certificates file
  ansible.builtin.file:
    path: ~/.mutt/certificates
    state: touch
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0655"

- name: Copy mutt user file for raithlin
  ansible.builtin.copy:
    src: user-raithlin
    dest: ~/.mutt/
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy the mutt user file for gmail
  ansible.builtin.copy:
    src: user-gmail
    dest: ~/.mutt/
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy the mutt signature file
  ansible.builtin.copy:
    src: batesste-signature
    dest: ~/.mutt/
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy the mutt language file
  ansible.builtin.copy:
    src: en_CA
    dest: ~/.mutt/lang/en_CA
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy the mutt configuration file
  ansible.builtin.copy:
    src: muttrc
    dest: ~/.mutt/muttrc
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy the mutt token file for Raithlin
  ansible.builtin.copy:
    src: sbates@raithlin.com.token
    dest: ~/.mutt/tokens
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0600"

- name: Copy the mutt token file for Gmail
  ansible.builtin.copy:
    src: sbates130272@gmail.com.token
    dest: ~/.mutt/tokens
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0600"

- name: Copy the mutt_oauth2.py file
  ansible.builtin.copy:
    src: mutt_oauth2.py
    dest: ~/.mutt/scripts/
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Replace the Google Client Secret token with the actual value from vault
  ansible.builtin.replace:
    path: ~/.mutt/scripts/mutt_oauth2.py
    regexp: "<GOOGLE_CLIENT_SECRET>"
    replace: "{{ google_oauth2_client_secret }}"

- name: Update .bashrc with some mutt specific environment variables.
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    owner: "{{ username }}"
    group: "{{ username }}"
    state: present
    create: true
    marker_begin: "BEGIN (mutt_setup)" 
    marker_end: "END (mutt_setup)" 
    block: |
      EMAIL=sbates@raithlin.com
      export EMAIL
      MAIL=~/.mutt/MAIL
      export MAIL
