---
galaxy_info:
  author: Stephen Bates
  company: Raithlin Semiconductors
  role_name: check_platform
  description: >-
    Validate host platform against role requirements
  license: Apache-2.0
  min_ansible_version: "8.2.0"
  platforms:
    - name: Ubuntu
      versions:
        - noble
        - resolute
  galaxy_tags:
    - validation
    - platform

dependencies: []
