---
# Copyright (c) Stephen Bates, 2026
#
# SPDX-License-Identifier: Apache-2.0

ansible_host: crs-spur.crusoe.amd.com
ansible_user: stebates
ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
username: stebates
user_setup_motd: true
host_sudo: none
user_setup_unprivileged: true
git_setup_unprivileged: true
claude_setup_unprivileged: true
