---
# Copyright (c) Stephen Bates, 2026
#
# SPDX-License-Identifier: Apache-2.0

ansible_host: rocm-ernic
ansible_ssh_port: 2222
user_setup_vm_fstab: true
user_setup_motd: true
rocm_setup_user: stebates
rocm_setup_run_checks: true
rdma_setup_install_rdma_exporter: true
rdma_setup_motd: true
nvme_exporter_setup_install: true
uprof_setup_deb_path: /var/lib/amduprof/amduprof_5.3-518_amd64.deb
