---
# Copyright (c) Stephen Bates, 2022
#
# Clone and update the tmux-scripts repo. Note we set the repo as a
# git-based remote so this can only run once my private ssh key is
# installed.

- name: Checkout tmux-scripts
  ansible.builtin.git:
    repo: "{{ (username == 'batesste') | ternary('git@github.com:sbates130272/tmux-scripts.git', 'https://github.com/sbates130272/tmux-scripts.git') }}"
    dest: ~/.tmux
    accept_hostkey: true
    force: "{{ tmux_setup_force }}"
    version: "{{ tmux_setup_sha }}"
