---
galaxy_info:
  author: Stephen Bates
  company: Raithlin Semiconductors
  role_name: rdma_setup
  description: >-
    Install RDMA software and InfiniBand tools
  license: Apache-2.0
  min_ansible_version: "8.2.0"
  platforms:
    - name: Ubuntu
      versions:
        - noble
        - resolute
  galaxy_tags:
    - system
    - rdma

dependencies: []
