(require 'package)
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")))
(package-initialize)
(unless (file-exists-p (concat package-user-dir "/archives"))
  (package-refresh-contents))
