---
# Copyright (c) Stephen Bates, 2026
#
# SPDX-License-Identifier: Apache-2.0

lemonade_setup_install_method: deb
lemonade_setup_host: "0.0.0.0"
lemonade_setup_port: 8000
lemonade_setup_log_level: info
lemonade_setup_max_loaded_models: 3
lemonade_setup_ctx_size: 131072
lemonade_setup_exporter_enabled: true
lemonade_setup_exporter_port: 9091
