---
galaxy_info:
  author: Stephen Bates
  company: Raithlin Semiconductors
  role_name: qemu_setup
  description: >-
    Install QEMU/KVM, libvirt, and configure networking
  license: Apache-2.0
  min_ansible_version: "2.15.0"
  platforms:
    - name: Ubuntu
      versions:
        - noble
        - resolute
  galaxy_tags:
    - qemu
    - kvm
    - virtualization
    - libvirt

dependencies: []
