---
# Copyright (c) Stephen Bates, 2022
#
# Create the user and make them a sudoer. Also copy in the SSH
# key file so one can use it inside the new machine. Also make sure
# one is a password-less sudo so we can execute other roles as
# myself.

- name: Set a fact containing the current roles' path
  ansible.builtin.set_fact:
    calling_role_path_fact: "{{ role_path }}"

- name: Test the host platform to see if it can support this role
  ansible.builtin.include_role:
    name: check_platform
  vars:
    calling_role_path: "{{ calling_role_path_fact }}"

- name: Ensure the user and admin groups exist
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop:
    - users
    - admin

- name: Create an account for the specified user
  ansible.builtin.user:
    name: "{{ username }}"
    groups: users,admin
    append: true
    shell: /bin/bash
  become: true

- name: Set authorized key for the user from local file
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Set user as passwordless sudoer
  ansible.builtin.blockinfile:
    path: /etc/sudoers.d/10-ansible-added-users
    owner: root
    group: root
    state: present
    create: true
    mode: "0644"
    block: |
      # Added by Ansible
      {{ username }} ALL=(ALL) NOPASSWD:ALL
  become: true

- name: Copy SSH private key
  ansible.builtin.copy:
    force: true
    src: ~/.ssh/id_rsa
    dest: /home/{{ username }}/.ssh/id_rsa
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0600"

- name: Copy SSH public key
  ansible.builtin.copy:
    force: true
    src: ~/.ssh/id_rsa.pub
    dest: /home/{{ username }}/.ssh/id_rsa.pub
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0644"

- name: Ensure users can access dmesg without sudo # noqa: args[module]
  ansible.builtin.blockinfile:
    path: /etc/sysctl.d/10-kernel-hardening.conf
    state: present
    create: false
    marker_begin: BEGIN (user-setup)
    marker_end: END (user-setup)
    block: |
      kernel.dmesg_restrict = 0
  become: true

- name: Restart procps service so dmesg rule takes effect # noqa: args[module]
  ansible.builtin.service:
    service: procps
    state: restarted
  become: true

- name: Massively improve startup on certain systems
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/systemd-networkd-wait-online.service
    search_string: ExecStart
    line: ExecStart=/lib/systemd/systemd-networkd-wait-online --any
  become: true

- name: Restart service # noqa: args[module]
  ansible.builtin.service:
    service: network-online.target
    state: restarted
  become: true

- name: Ensure package install is non-interactive
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    state: present
    marker_begin: BEGIN (user_setup)
    marker_end: END (user_setup)
    block: |
      export DEBIAN_FRONTEND=noninteractive
  become: true

- name: Set the timezone of the system clock
  community.general.timezone:
    name: "{{ user_setup_timezone }}"
  become: true

- name: Ensure SSH config file exists for user and create a Host * when absent
  ansible.builtin.lineinfile:
    path: /home/{{ username }}/.ssh/config
    line: Host *
    state: present
    create: true
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0644"

- name: Set important values in user's ssh config file
  ansible.builtin.lineinfile:
    path: /home/{{ username }}/.ssh/config
    line: "{{ item }}"
    insertafter: Host *
    state: present
    create: false
  loop:
    - ServerAliveInterval 60
    - ServerAliveCountMax 30
    - StrictHostKeyChecking accept-new

- name: Ensure .emacs.d folder exists
  ansible.builtin.file:
    path: /home/{{ username }}/.emacs.d
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Copy emacs config file from our files folder
  ansible.builtin.copy:
    force: true
    src: init.el
    dest: /home/{{ username }}/.emacs.d/init.el
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0644"

- name: Copy emacs config file from our files folder
  ansible.builtin.copy:
    force: true
    src: .emacs
    dest: /home/{{ username }}/.emacs
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0644"

- name: Create Projects folder if it does not exist
  ansible.builtin.file:
    path: /home/{{ username }}/Projects
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  when: user_setup_vm_fstab

- name: Add an entry in fstab for VM virtio-fs
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "hostfs /home/{{ username }}/Projects 9p trans=virtio,version=9p2000.L,nofail 0 1"
    state: present
  become: true
  when: user_setup_vm_fstab

- name: Perform a systemctl daemon-reload and restart of mount
  ansible.builtin.service:
    service: home-{{ username }}-Projects.mount
    state: restarted
    daemon_reload: true
  become: true
  when: user_setup_vm_fstab
