---
# Copyright (c) Stephen Bates, 2022
#
#
# Update cache and install favourite packages.

- name: Install my favourite packages
  ansible.builtin.package:
    update_cache: true
    name:
      - bmon
      - build-essential
      - emacs-nox
      - fio
      - git
      - gnuplot
      - gpg-agent
      - libaio-dev
      - liburing-dev
      - prometheus-node-exporter
      - prometheus-node-exporter-collectors
      - python-is-python3
      - python2
      - python3-pip
      - mutt
      - sysstat
      - tmux
      - tree
      - xfsprogs
    state: present
