---
# Copyright (c) Stephen Bates, 2022
#
#
# Update cache and install favourite packages.

- name: Install my favourite packages
  ansible.builtin.package:
    update_cache: true
    name:
      - bmon
      - build-essential
      - emacs-nox
      - fio
      - git
      - gnuplot
      - gpg-agent
      - libaio-dev
      - liburing-dev
      - prometheus-node-exporter
      - prometheus-node-exporter-collectors
      - python2
      - python3-pip
      - mutt
      - sysstat
      - tmux
      - tree
      - xfsprogs
    state: present

- name: Symbolic link from python2 to python
  ansible.builtin.file:
    src: /usr/bin/python2
    path: /usr/bin/python
    state: link
