# Copyright (c) Stephen Bates, 2022
#
# Create the user batesste and make them a sudoer. Also copy in my SSH
# key file so I can use it inside the new machine.

- name: Update package cache (assumes apt)
  ansible.builtin.apt:
    update_cache: yes

- name: Install my favourite packages
  ansible.builtin.package:
    name:
      - build-essential
      - emacs-nox
      - fio
      - git
      - sysstat
      - tree
    state: latest
