---
# Copyright (c) Stephen Bates, 2022
#
#
# Update cache and install favourite packages.

- name: Set a fact containing the current roles' path
  ansible.builtin.set_fact:
    calling_role_path_fact: "{{ role_path }}"

- name: Test the host platform to see if it can support this role
  ansible.builtin.include_role:
    name: check_platform
  vars:
    calling_role_path: "{{ calling_role_path_fact }}"

- name: Install my favourite packages
  ansible.builtin.package:
    update_cache: true
    name:
      - bmon
      - build-essential
      - cmake
      - driverctl
      - emacs-nox
      - expect
      - fio
      - git
      - gnuplot
      - gpg-agent
      - libaio-dev
      - liburing-dev
      - prometheus-node-exporter
      - prometheus-node-exporter-collectors
      - python-is-python3
      - python3
      - python3-pip
      - python3-venv
      - mutt
      - sysstat
      - tmux
      - tree
      - xfsprogs
    state: present
  become: true

- name: Install my favourite packages on noble
  ansible.builtin.package:
    update_cache: true
    name:
      - elpa-cmake-mode
      - elpa-rust-mode
      - virtiofsd
  become: true
  when:
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_release'] == "noble"
