# Copyright (c) Stephen Bates, 2022
#
# Clone the upstream fio repo from Jens and checkout the SHA given by
# the associated input variable. Also ensure the packages required to
# run specific tests are included and also update this version of fio
# to the PATH.

- name: Update cache and install fio related favourite packages
  ansible.builtin.package:
    update_cache: yes
    name:
      - gettext
      - libaio-dev
      - libnuma-dev
      - libpci-dev
      - libpmem-dev
      - libpmem2-dev
      - liburing-dev
      - linux-tools-common
      - nvme-cli
      - pkg-config
  become: yes

- name: Gather the kernel fact on the remote when on AWS
  ansible.builtin.setup:
    gather_subset:
      - kernel
  when: inventory_hostname in groups['awsmachines']

- name: Install fio related favourite packages when on AWS
  ansible.builtin.package:
    name:
      - linux-tools-{{ ansible_kernel }}
      - linux-tools-aws
  become: yes
  when: inventory_hostname in groups['awsmachines']

- name: Checkout upstream fio repo from Github
  ansible.builtin.git:
    repo: https://github.com/axboe/fio.git
    dest: ~/fio
    force: yes
    version: '{{ fio_tag }}'

- name: Configure fio and record output of the configuration
  ansible.builtin.shell:
    chdir: ~/fio
    cmd: ./configure --prefix='{{ fio_install_dir }}' | tee config.tee

- name: Make fio
  ansible.builtin.shell:
    chdir: ~/fio
    cmd: make -j ${nproc}

- name: Install fio in desired folder
  ansible.builtin.shell:
    chdir: /home/{{ username }}/fio
    cmd: make install
  become: yes
