---
# Copyright (c) Stephen Bates, 2022
#
# Clone the upstream fio repo from Jens and checkout the SHA given by
# the associated input variable. Also ensure the packages required to
# run specific tests are included and also update this version of fio
# to the PATH.

- name: Install fio related packages
  ansible.builtin.package:
    name:
      - gettext
      - libaio-dev
      - libnuma-dev
      - libpci-dev
      - libpmem-dev
      - libpmem2-dev
      - liburing-dev
      - linux-tools-common
      - nvme-cli
      - pkg-config
  become: true

- name: Gather the kernel fact on the remote when on AWS
  ansible.builtin.setup:
    gather_subset:
      - kernel
  when: inventory_hostname in groups['awsmachines']

- name: Install fio related packages when on AWS
  ansible.builtin.package:
    name:
      - linux-tools-{{ ansible_kernel }}
      - linux-tools-aws
  become: true
  when: inventory_hostname in groups['awsmachines']

- name: Ensure Projects folder exists.
  ansible.builtin.file:
    path: ~/Projects
    state: directory
    mode: "0755"

- name: Checkout upstream fio repo from Github
  ansible.builtin.git:
    repo: https://github.com/axboe/fio.git
    dest: ~/Projects/fio
    force: true
    version: "{{ fio_tag }}"
  notify: Configure, build and install fio
