---
# the default user is batesste
username: batesste
user_setup_timezone: America/Edmonton

# Do we want to fstab in a VM
user_setup_vm_fstab: false

# Enable MOTD showing driver overrides
user_setup_motd: false

# SSH key filename stem (e.g. id_rsa, id_ed25519)
user_setup_ssh_key_name: id_rsa

# Controller-side directory containing the SSH keys
user_setup_ssh_key_src_dir: "{{ lookup('env', 'HOME') }}/.ssh"
