---
# Copyright (c) Stephen Bates, 2022
#
#
# Update cache and install favourite packages.

- name: Install my favourite packages
  ansible.builtin.package:
    update_cache: true
    name:
      - bmon
      - build-essential
      - emacs-nox
      - fio
      - git
      - gpg-agent
      - libaio-dev
      - liburing-dev
      - mutt
      - sysstat
      - tree
    state: present
