---
galaxy_info:
  author: Stephen Bates
  company: Raithlin Semiconductors
  role_name: nvmeof_setup
  description: >-
    Setup NVMe-oF targets and hosts
  license: Apache-2.0
  min_ansible_version: "2.15.0"
  platforms:
    - name: Ubuntu
      versions:
        - noble
        - resolute
  galaxy_tags:
    - nvme
    - storage
    - rdma

dependencies: []
