---
galaxy_info:
  author: Stephen Bates
  company: Raithlin Semiconductors
  role_name: aws_grub
  description: >-
    Configure GRUB for AWS cloud images
  license: Apache-2.0
  min_ansible_version: "8.2.0"
  platforms:
    - name: Ubuntu
      versions:
        - noble
        - resolute
  galaxy_tags:
    - aws
    - grub
    - cloud

dependencies: []
