---
galaxy_info:
  author: Stephen Bates
  company: Raithlin Semiconductors
  role_name: tmux_scripts
  description: >-
    Install tmux plugins and configuration
  license: Apache-2.0
  min_ansible_version: "2.15.0"
  platforms:
    - name: Ubuntu
      versions:
        - noble
        - resolute
  galaxy_tags:
    - tmux
    - terminal

dependencies: []
