---
galaxy_info:
  author: Stephen Bates
  company: Raithlin Semiconductors
  role_name: github_runner
  description: >-
    Install and configure GitHub self-hosted runners
  license: Apache-2.0
  min_ansible_version: "2.15.0"
  platforms:
    - name: Ubuntu
      versions:
        - noble
        - resolute
  galaxy_tags:
    - github
    - ci
    - runner

dependencies: []
