---
galaxy_info:
  author: Stephen Bates
  company: Raithlin Semiconductors
  role_name: consul_setup
  description: >-
    Install and configure HashiCorp Consul and node exporter
  license: Apache-2.0
  min_ansible_version: "2.15.0"
  platforms:
    - name: Ubuntu
      versions:
        - noble
        - resolute
  galaxy_tags:
    - consul
    - monitoring
    - hashicorp

dependencies: []
