---
# Copyright (c) Stephen Bates, 2026
#
# SPDX-License-Identifier: Apache-2.0
#

all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local

    aws_ec2_launch:
      hosts:
        localhost:
          ansible_connection: local

    aws_rocm_bootstrap:
      hosts:
        aws-rocm-xio-target:
          ansible_user: ubuntu

    awsmachines:
      hosts:
        aws-rocm-xio-target:
          ansible_user: ubuntu

    localvms:
      hosts:
        local-vm:

    amd:
      hosts:
        amd-oracle:
          ansible_host: amd-oracle
          ansible_ssh_common_args: >-
            -o RequestTTY=no
            -o RemoteCommand=none
        weka-client:
          ansible_host: weka-client
        weka-server:
          ansible_host: weka-server
        hipfile-9:
        hipfile-10:
        ibgda-ctrl:
        snoc-strix:
        snoc-think:
        snoc-think-vm:
        ibgda-brcm:
        local-vm:
        rocm-ernic-vm:
          ansible_host: rocm-ernic
          ansible_ssh_port: 2222
        rocm-ernic-vm-alola:
          ansible_host: 10.7.197.12
          ansible_user: stebates
        hipfile-9-vm:
          ansible_host: hipfile-9
          ansible_ssh_port: 2222

    pliops:
      hosts:
        pliops-storage:
        pliops-gpu:
          ansible_user: amd

    nvmeof:
      hosts:
        nvmeof-hosts:
          ansible_host: snoc-think
        nvmeof_targets:
          ansible_host: snoc-think-vm

    weka_oci:
      hosts:
        weka-server-vm-10:
          ansible_host: useocpm2m-097-114
          ansible_port: 2230
          ansible_ssh_common_args: '-o ProxyJump=useocpslog-002'

    weka_local:
      hosts:
        weka-server-vm-1:
          ansible_host: snoc-think
          ansible_port: 2230
        weka-server-vm-2:
          ansible_host: snoc-think
          ansible_port: 2231

    rdma:
      hosts:
        snoc-think:
          ansible_host: snoc-think
        snoc-think-vm:
          ansible_host: snoc-think-vm

    pensando:
      hosts:
        pensando-01:
          ansible_host: pens-01
          ansible_user: batesste
        smci355-ccs-aus-m03-21:
          ansible_host: 10.235.27.194
          ansible_user: batesste
        smci355-ccs-aus-m03-25:
          ansible_host: 10.235.25.94
          ansible_user: batesste
