---
# Copyright (c) Stephen Bates, 2026
#
# Build and validate ROCm XIO on AMD hosts.
#

- name: Build and validate rocm-xio on AMD hosts
  hosts: "{{ targets }}"
  gather_facts: true
  roles:
    - role: sbates130272.batesste.rocm_xio_setup
      remote_user: "{{ username }}"
      rocm_setup_user: "{{ username }}"
      tags: [rocm_xio_setup]
