# Copyright (c) Stephen Bates, 2022
#
# This playbook takes a brand new machine and adds me as a user and
# then setups up things the way I like. It also setups remove ssh and
# installs my ssh keys and gnupgp keyring. Note we assume an initial
# user on the machine called eid and this may need to be made a
# variable.

- name: Setup batesste account and install my favourite stuff on a new machine
  hosts: awsmachines
  gather_facts: no
  roles:
    - role: "add-batesste"
      remote_user: "{{ root_user }}"
      become: yes
      tags: [add-batesste]
    - role: "fave-packages"
      remote_user: batesste
      become: yes
      tags: [fave-packages]
    - role: "tmux-scripts"
      remote_user: batesste
      become: no
      tags: [tmux-scripts]
    - role: "eideticom-scripts"
      remote_user: batesste
      become: no
      tags: [eideticom-scripts]
    - role: "git-setup"
      remote_user: batesste
      become: no
      tags: [git-setup]
    - role: "mutt-setup"
      remote_user: batesste
      become: no
      tags: [mutt-setup]
    - role: "kernel-setup"
      remote_user: batesste
      become: no
      tags: [kernel-setup]
    - role: "fio-devel"
      remote_user: batesste
      become: no
      tags: [fio-devel]
