---
# Copyright (c) Stephen Bates, 2022
#
# This playbook takes a brand new machine and adds a user and then
# setups up things the way I like. It also setups remote ssh and
# installs my ssh keys and gnupgp keyring. Note we assume an initial
# user on the machine given by the {{ root_user }} variable.

- name: Setup user account and install cool stuff on a new machine
  hosts: "{{ targets }}"
  gather_facts: false
  roles:
    - role: user-setup
      remote_user: "{{ root_user }}"
      become: true
      tags: [user-setup]
    - role: fave-packages
      remote_user: "{{ username }}"
      become: true
      tags: [fave-packages]
    - role: git-setup
      remote_user: "{{ username }}"
      become: false
      tags: [git-setup]
    - role: tmux-scripts
      remote_user: "{{ username }}"
      become: false
      tags: [tmux-scripts]
    - role: eideticom-scripts
      remote_user: "{{ username }}"
      become: false
      tags: [eideticom-scripts]
    - role: mutt-setup
      remote_user: "{{ username }}"
      become: false
      tags: [mutt-setup]
    - role: kernel-setup
      remote_user: "{{ username }}"
      become: false
      tags: [kernel-setup]
    - role: fio-devel
      remote_user: "{{ username }}"
      become: false
      tags: [fio-devel]
    - role: aws-grub
      remote_user: "{{ username }}"
      become: true
      tags: [aws-grub]
      when: inventory_hostname in groups['awsmachines']
    - role: qemu-setup
      remote_user: "{{ username }}"
      become: false
      tags: [qemu-setup]
      when: inventory_hostname not in groups['localvms']
