---
# Copyright (c) Stephen Bates, 2022
#
# This playbook takes a brand new machine and adds a user and then
# setups up things the way I like. It also setups remote ssh and
# installs my ssh keys and gnupgp keyring. Note we assume an initial
# user on the machine given by the {{ root_user }} variable.

- name: Setup user account and install cool stuff on a new machine
  hosts: "{{ targets }}"
  gather_facts: true
  vars:
    force: false
    kernel_setup_force: "{{ force }}"
    kernel_setup_tools_force: "{{ force }}"
    qemu_setup_force: "{{ force }}"
    tmux_scripts_force: "{{ force }}"
    fio_devel_fio_force: "{{ force }}"
    fio_devel_fio_stuff_force: "{{ force }}"
  roles:
    - role: user_setup
      remote_user: "{{ root_user }}"
      become: true
      tags: [user_setup]
    - role: fave_packages
      remote_user: "{{ username }}"
      become: true
      tags: [fave_packages]
    - role: git_setup
      remote_user: "{{ username }}"
      become: false
      tags: [git_setup]
    - role: tmux_scripts
      remote_user: "{{ username }}"
      become: false
      tags: [tmux_scripts]
    - role: cloud_setup
      remote_user: "{{ username }}"
      become: false
      tags: [cloud_setup]
      when:
        - ansible_facts['distribution'] == "Ubuntu"
        - ansible_facts['distribution_release'] == "jammy"
    - role: consul_setup
      remote_user: "{{ username }}"
      become: false
      tags: [consul_setup]
      when:
        - ansible_facts['distribution'] == "Ubuntu"
        - ansible_facts['distribution_release'] == "jammy"
    - role: mutt_setup
      remote_user: "{{ username }}"
      become: false
      tags: [mutt_setup]
    - role: kernel_setup
      remote_user: "{{ username }}"
      become: false
      tags: [kernel_setup]
    - role: fio_devel
      remote_user: "{{ username }}"
      become: false
      tags: [fio_devel]
    - role: geerlingguy.docker
      docker_edition: 'ce'
      docker_users:
        - "{{ username }}"
      become: true
      tags: [docker_setup]
    - role: aws_grub
      remote_user: "{{ username }}"
      become: true
      tags: [aws_grub]
      when:
        - inventory_hostname in groups['awsmachines']
    - role: qemu_setup
      remote_user: "{{ username }}"
      become: false
      tags: [qemu_setup]
      when:
        - inventory_hostname not in groups['localvms'] and
          inventory_hostname not in groups['runners']
    - role: vm_create
      remote_user: "{{ username }}"
      become: false
      tags: [vm_create]
      when:
        - inventory_hostname not in groups['localvms'] and
          inventory_hostname not in groups['runners']
