# Copyright (c) Stephen Bates, 2022
#
# Set up git just the way I like it. This includes Gnupg signing,
# editor setup, name and email (global for {{ username }}). Note this
# assumes some other roles have been run before this one.
#
# Note some of these tasks need:
#
# ansible-galaxy collection install community.general

- name: Copy over gnupg folder to ensure PGP keys are on target(s)
  ansible.posix.synchronize:
    src: ~/.gnupg/
    dest: ~/.gnupg/
    rsync_opts:
       - "--exclude=S.*"
       - "--exclude=*~"

- name: Setup emacs as git editor
  community.general.git_config:
    name: core.editor
    value: emacs
    scope: global

- name: Setup name for git config
  community.general.git_config:
    name: user.name
    value: Stephen Bates
    scope: global

- name: Setup email for git config
  community.general.git_config:
    name: user.email
    value: sbates@raithlin.com
    scope: global

- name: Setup pgp signing for all commits
  community.general.git_config:
    name: commit.gpgsign
    value: "true"
    scope: global

- name: Setup pgp signing for all commits
  community.general.git_config:
    name: user.signingkey
    value: CB05CB5CFA5DFD9850BB814DE0C020C1975548AE
    scope: global

- name: Setup gpg-agent correctly in .bashrc
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    owner: "{{ username }}"
    group: "{{ username }}"
    state: present
    create: true
    marker_begin: "BEGIN (git_setup)"
    marker_end: "END (git_setup)"
    block: |
      GPG_TTY=$(tty)
      export GPG_TTY

- name: Setup default merge behaviour
  community.general.git_config:
    name: pull.rebase
    value: "false"
    scope: global
